### ISSUE TITLE
SDB install error 

### ISSUE THREAD

**Issue by rklra** [SnellerInc/sneller#8]
Hi, I was installing the SDB package and encountered the following errors:

The host CPU is a Xeon W-2145 that I verified has AVX-512 capability (per instructions in README)

The errors I got on install are (abridged) below:
```
go install github.com/SnellerInc/sneller/cmd/sdb@latest
[...]
# github.com/SnellerInc/sneller/vm
.go/pkg/mod/github.com/!sneller!inc/sneller@v0.0.0-20240102170256-76df1cd580a0/vm/interp.go:550:31: undefined: bcaggminf
.go/pkg/mod/github.com/!sneller!inc/sneller@v0.0.0-20240102170256-76df1cd580a0/vm/interp.go:551:31: undefined: bcaggmaxf
.go/pkg/mod/github.com/!sneller!inc/sneller@v0.0.0-20240102170256-76df1cd580a0/vm/interp.go:552:31: undefined: bcaggmini
.go/pkg/mod/github.com/!sneller!inc/sneller@v0.0.0-20240102170256-76df1cd580a0/vm/interp.go:553:31: undefined: bcaggmaxi
```

I was able to solve the error in the `go install` command by commenting out these lines manually in the interp.go file, though I do not know if this is a valid solution

Following the rest of the directions for the demo in the README it appears to have solved the issue.

**Comment by HJLebbink** [comment]
@rklra 

Thank you for reporting this, It has been fixed, but I need to check how this will trickle down into this repo. Quoting out the four lines is fine as long you are not using the portable (non-AVX12) version.

**Comment by HJLebbink** [comment]
fixed!
